snapshot:
  retention: 168h

dbs:
  - path: /data/spanbox.db
    replica:
      type: s3
      bucket: ${LITESTREAM_BUCKET}
      path: spanbox
      endpoint: ${LITESTREAM_ENDPOINT}
      access-key-id: ${LITESTREAM_ACCESS_KEY_ID}
      secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY}
      sync-interval: 1s
